# Generated by Django 4.2.29 on 2026-03-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptive_pdf',
            field=models.FileField(blank=True, help_text='PDF document with product details and specifications', null=True, upload_to='products/pdfs/', verbose_name='Descriptive document (PDF)'),
        ),
    ]
